CREATE SCHEMA IF NOT EXISTS user_mgmt;

CREATE TABLE IF NOT EXISTS user_mgmt.users (
  id UUID PRIMARY KEY,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  phone_number VARCHAR(24) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_mgmt.user_addresses (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  label VARCHAR(64) NOT NULL,
  line1 VARCHAR(200) NOT NULL,
  city VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
