CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS user_mgmt;
CREATE SCHEMA IF NOT EXISTS vendor_mgmt;
CREATE SCHEMA IF NOT EXISTS menu_mgmt;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS payment_mgmt;
CREATE SCHEMA IF NOT EXISTS delivery_mgmt;
CREATE SCHEMA IF NOT EXISTS subscription_mgmt;
CREATE SCHEMA IF NOT EXISTS feedback_mgmt;
