spring:
  application:
    name: order-service
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
